### PR TITLE
remove check-ignore-label.gatekeeper.sh from validatingwebhook

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/11401

This removed the check-ignore-label.gatekeeper.sh rule from the
validatingwebhook which is used by gatekeeper to ensure only given namespaces
(default to gatekeeper-system) can have the admission.gatekeeper.sh/ignore label
and therefore be ignored by gatekeeper.

We should be safe without this because addind the ignore label on a
namespace is a conscious action, therefore we know what we are doing.

This was tested on a tenant cluster:
* deploy gatekeeper withouth the `check-ignore-label.gatekeeper.sh` rule
* ensure it is not running

* apiserver keep throwing lot of error due to gatekeeper not being reachable
* create/delete/update namespaces works

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by TheoBrigitte** [comment]
I'd like to see if @giantswarm/wg-opa agrees with this.

**Comment by paurosello** [comment]
Fine by me, should not affect too much and less webhooks that can go wrong

**Comment by kopiczko** [comment]
I'm not against that but I don't understand how that helps with the linked issue.

**Comment by TheoBrigitte** [comment]
> I'm not against that but I don't understand how that helps with the linked issue.

I believe it does help because the APIserver would fail when there is a `CREATE` or `UPDATE` request made to a namespace but gatekeeper is down.

**Comment by TheoBrigitte** [comment]
NOTE: test this by rebooting master node on kvm

**Pull request merged**
