### PR TITLE
Moving crds into a different dir

### PR DESCRIPTION
**Pull request by tomahawk28**
Toward https://github.com/giantswarm/giantswarm/issues/11075

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Did you see the [Sync chart with upstream](https://github.com/giantswarm/gatekeeper-app#sync-chart-with-upstream) section in the readme? Could you follow the instructions there so we have a patch with the changes and can update from upstream?

**Comment by tomahawk28** [comment]
@ubergesundheit Thanks for notice, I will follow up with that.

**Comment by tomahawk28** [comment]
Helm 2 install/upgrade testing done, works fine.

**Comment by tomahawk28** [comment]
helm3 install failed, since CRD still have pre-install hook. I think we should apply the same approach as kong, set `crdInstall`  values default as false in `values.yaml`.

**Comment by rossf7** [comment]
> I think we should apply the same approach as kong, set crdInstall values default as false in values.yaml.

How do we set that value though? Is there a way in the templating to know if it's Helm 2 or 3?

**Comment by tomahawk28** [comment]
> How do we set that value though? Is there a way in the templating to know if it's Helm 2 or 3?

I looked into built-in objects but could not find helm version information at there. 
https://helm.sh/docs/chart_template_guide/builtin_objects/
Sadly, we need another approach if we should count helm3 install.

**Comment by tomahawk28** [comment]
Now I confirmed it works in either Helm 2, 3. Both install/upgrade.

**Comment by tomahawk28** [comment]
@ubergesundheit Would you like to review it again? There are some differences between the last status.

**Pull request merged**
